{ pkgs ? import <nixpkgs> { } }:

pkgs.mkShell {
  name = "rust-rdma-bench";

  # Build-time tools. `ibverbs-sys` vendors rdma-core and builds it from
  # source via CMake, so these need to be on PATH even though we never
  # depend on a system libibverbs directly.
  nativeBuildInputs = with pkgs; [
    pkg-config
    cmake
    python3
    clang
  ];

  # Libraries rdma-core's CMake build links against.
  buildInputs = with pkgs; [
    rustc
    cargo
    rustfmt
    clippy
    rust-analyzer

    libnl
    udev

    # ibverbs-sys generates its FFI bindings with bindgen, which needs
    # libclang at build time.
    llvmPackages.libclang

    # Supplies infiniband/verbs_api.h for bindgen; see the comment on
    # BINDGEN_EXTRA_CLANG_ARGS below.
    rdma-core
    rdma-core.dev
  ];

  LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";

  # bindgen calls into libclang directly rather than going through a
  # nixpkgs-wrapped `clang` binary, so it doesn't pick up the usual
  # automatic include-path setup. It needs:
  #
  #   - clang's own freestanding headers (stddef.h, stdarg.h, ...) from
  #     the compiler's resource dir,
  #   - glibc's headers (stdint.h, sched.h, ...),
  #   - infiniband/verbs_api.h.
  #
  # That last one is generated by ibverbs-sys's CMake build into
  # $OUT_DIR/build/include, but its build.rs passes bindgen
  # `-I$OUT_DIR/include` -- a directory that does not exist. On ordinary
  # distros this goes unnoticed because clang falls back to
  # /usr/include/infiniband, which NixOS has no equivalent of, so point
  # bindgen at nixpkgs' rdma-core headers instead. Note this makes the
  # generated bindings a blend of the vendored rdma-core (verbs.h, passed
  # to bindgen by explicit path) and nixpkgs' (verbs_api.h), which are
  # not necessarily the same upstream release.
  BINDGEN_EXTRA_CLANG_ARGS =
    let
      libclang = pkgs.llvmPackages.libclang;
      clangVersion = pkgs.lib.versions.major libclang.version;
    in
    "-isystem ${libclang.lib}/lib/clang/${clangVersion}/include "
    + "-isystem ${pkgs.glibc.dev}/include "
    + "-isystem ${pkgs.rdma-core.dev}/include";
}
